// <auto-generated />
using System;
using LLMDiscordBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLMDiscordBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20251115144608_AddGuildIdToTokenUsageAndChatHistory")]
    partial class AddGuildIdToTokenUsageAndChatHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("LLMDiscordBot.Models.BotSettings", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("BotSettings");

                    b.HasData(
                        new
                        {
                            Key = "Model",
                            UpdatedAt = new DateTime(2025, 11, 15, 14, 46, 7, 549, DateTimeKind.Utc).AddTicks(4082),
                            Value = "default"
                        },
                        new
                        {
                            Key = "Temperature",
                            UpdatedAt = new DateTime(2025, 11, 15, 14, 46, 7, 549, DateTimeKind.Utc).AddTicks(4083),
                            Value = "0.7"
                        },
                        new
                        {
                            Key = "GlobalMaxTokens",
                            UpdatedAt = new DateTime(2025, 11, 15, 14, 46, 7, 549, DateTimeKind.Utc).AddTicks(4084),
                            Value = "2000"
                        },
                        new
                        {
                            Key = "GlobalSystemPrompt",
                            UpdatedAt = new DateTime(2025, 11, 15, 14, 46, 7, 549, DateTimeKind.Utc).AddTicks(4085),
                            Value = "You are a helpful AI assistant."
                        },
                        new
                        {
                            Key = "GlobalDailyLimit",
                            UpdatedAt = new DateTime(2025, 11, 15, 14, 46, 7, 549, DateTimeKind.Utc).AddTicks(4086),
                            Value = "100000"
                        });
                });

            modelBuilder.Entity("LLMDiscordBot.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ChannelId", "Timestamp");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.GuildAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("GuildAdmins");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DailyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLimits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.TokenUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("TokenUsages");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyTokenLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsBlocked");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.ChatHistory", b =>
                {
                    b.HasOne("LLMDiscordBot.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.TokenUsage", b =>
                {
                    b.HasOne("LLMDiscordBot.Models.User", "User")
                        .WithMany("TokenUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.User", b =>
                {
                    b.Navigation("ChatHistories");

                    b.Navigation("TokenUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
