// <auto-generated />
using System;
using LLMDiscordBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLMDiscordBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20251119171907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("LLMDiscordBot.Models.BotSettings", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("BotSettings");

                    b.HasData(
                        new
                        {
                            Key = "Model",
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 19, 7, 29, DateTimeKind.Utc).AddTicks(2178),
                            Value = "default"
                        },
                        new
                        {
                            Key = "Temperature",
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 19, 7, 29, DateTimeKind.Utc).AddTicks(2180),
                            Value = "0.7"
                        },
                        new
                        {
                            Key = "GlobalMaxTokens",
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 19, 7, 29, DateTimeKind.Utc).AddTicks(2181),
                            Value = "2000"
                        },
                        new
                        {
                            Key = "GlobalDailyLimit",
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 19, 7, 29, DateTimeKind.Utc).AddTicks(2183),
                            Value = "100000"
                        });
                });

            modelBuilder.Entity("LLMDiscordBot.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId", "ChannelId", "Timestamp");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.GuildAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("GuildAdmins");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DailyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLimits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.InteractionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseLength")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicCategory")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UserSatisfied")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandType");

                    b.HasIndex("GuildId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("InteractionLogs");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.TokenUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId", "GuildId", "Date")
                        .IsUnique();

                    b.ToTable("TokenUsages");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyTokenLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsBlocked");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.UserPreferences", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageMessageLength")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan?>("AverageSessionDuration")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomSystemPrompt")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableSmartSuggestions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FavoriteCommands")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastInteractionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MostUsedTopics")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferCodeExamples")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferStepByStep")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferVisualContent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferredMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredResponseStyle")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("PreferredTemperature")
                        .HasColumnType("REAL");

                    b.Property<string>("PreferredTimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RememberConversationContext")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalInteractions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("LastInteractionAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.ChatHistory", b =>
                {
                    b.HasOne("LLMDiscordBot.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.TokenUsage", b =>
                {
                    b.HasOne("LLMDiscordBot.Models.User", "User")
                        .WithMany("TokenUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.UserPreferences", b =>
                {
                    b.HasOne("LLMDiscordBot.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("LLMDiscordBot.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LLMDiscordBot.Models.User", b =>
                {
                    b.Navigation("ChatHistories");

                    b.Navigation("TokenUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
